config/routes.rb
Rails.application.routes.draw do

  resources :cprofiles, path: 'admin/company-profiles'

  resources :contacts

  resources :banners, path: 'admin/banners'

  devise_for :users, :path => '', :path_names => {:sign_in => 'cmp-login', :sign_out => 'logout', :sign_up => 'cmp-register'}

  resources :users, path: 'admin/users'

  get 'single/index'

  get ':slug' => 'single#index'

  get 'admin/dashboard' => 'admin#index'

  resources :properties, path: 'admin/properties'

  get '/properties/name' => 'properties#name'

  get '/properties/property_name' => 'properties#property_name'
  
  get '/home' => 'home#index'

  get '/home/development' => 'home#develop'

  get '/listing' => 'home#listing'

  get 'landing/index' => 'home#landing'

  get 'cmp/documentation' => 'home#dokumentasi'

  get 'react/latihan' => 'home#lat_react'

   root 'home#landing'

   mount Attachinary::Engine => "/attachinary"
   

end

app/models/banner.rb
class Banner < ActiveRecord::Base

  # validates :images, presence: true
  # has_attachments :images, maximum: 5, accept: [:jpg, :png, :gif]
  has_attachments :images, accept: [:jpg, :png, :gif]

end

app/controllers/banners_controller.rb
class BannersController < ApplicationController

  layout 'admin_layout'

  before_action :authenticate_user!
  before_action :set_banner, only: [:show, :edit, :update, :destroy]

  # GET /banners
  # GET /banners.json
  def index
    @banners        = Banner.all

    @jumlah_banner  = Banner.count

    # @properties     = Property.order("created_at DESC")

    @q = Property.ransack(params[:q])
    @properties = @q.result.order("created_at DESC").page(params[:page]).per_page(8)
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
  end

  # GET /banners/new
  def new
    @banner = Banner.new
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner, notice: 'Banner was successfully created.' }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1
  # PATCH/PUT /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to @banner, notice: 'Banner was successfully updated.' }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to banners_url, notice: 'Banner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banner_params
      params.require(:banner).permit(:name, :description, :images, :banner1, :banner2, :banner3, :banner4, :banner5, :banner6)
    end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<div class="container">
  <div class="col-lg-9 col-xs-12">
    <%= form_for(@banner) do |f| %>
      <% if @banner.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

          <ul>
          <% @banner.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name, class:"form-control" %>
      </div>
      <div class="field">
          <%= f.label :banner1 %><br>
          <%= f.text_field :banner1, class:"form-control" %>
      </div>

      <div class="field">
        <%= f.label :banner2 %><br>
        <%= f.text_field :banner2, class:"form-control" %>
      </div>

      <div class="field">
        <%= f.label :banner3 %><br>
        <%= f.text_field :banner3, class:"form-control" %>
      </div>

      <div class="field">
        <%= f.label :banner4 %><br>
        <%= f.text_field :banner4, class:"form-control" %>
      </div>

      <div class="field">
        <%= f.label :banner5 %><br>
        <%= f.text_field :banner5, class:"form-control" %>
      </div>

      <div class="field">
        <%= f.label :banner6 %><br>
        <%= f.text_field :banner6, class:"form-control" %>
      </div>

      <br><br>
    <div class="actions">
      <%= f.submit class:'btn btn-primary' %>
    </div>
  <% end %>
  </div>
</div>

app/views/banners/edit.html.erb
<div class="col-lg-9 col-lg-9 col-xs-12">
  <h1>Editing Banner</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @banner %> |
  <%= link_to 'Back', banners_path %>

</div>

app/views/banners/index.html.erb
<div class="col-lg-9 col-xs-12">
  <p id="notice"><%= notice %></p>

  <h1>Listing Banners</h1>
  <br>
  <i class="fa fa-plus-circle"></i>&nbsp;<%= link_to "Add New Banner", new_banner_path %> <br>
  <div class="alert alert-info" role="alert">
    <i>Menambahkan Banner hanya bila Banner masih kosong, untuk mengganti Banner cukup dengan EDIT,
    klik tombol EDIT untuk mengganti Banner lain.</i>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Image Url</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
    <% @banners.each do |banner| %>
    <tr>
        <td><%= banner.name %></td>
        <td>
          <dl>
            <dt>Banner1</dt>
            <dd><%= banner.banner1 %></dd>
          </dl>
          <dl>
            <dt>Banner2</dt>
            <dd><%= banner.banner2 %></dd>
          </dl>
          <dl>
            <dt>Banner3</dt>
            <dd><%= banner.banner3 %></dd>
          </dl>
          <dl>
            <dt>Banner4</dt>
            <dd><%= banner.banner4 %></dd>
          </dl>
          <dl>
            <dt>Banner5</dt>
            <dd><%= banner.banner5 %></dd>
          </dl>

        </td>
        <td><i class="glyphicon glyphicon-eye-open"></i><%= link_to 'Show', banner %></td>
        <td><i class="glyphicon glyphicon-pencil"></i><%= link_to 'Edit', edit_banner_path(banner) %></td>
        <td><i class="glyphicon glyphicon-remove"></i><%= link_to 'Remove', banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/banners/new.html.erb
<div class="col-lg-9 col-xs-12">
  <h1>New Banner</h1>

  <%= render 'form' %>

  <%= link_to 'Back', banners_path %>

</div>

app/views/banners/show.html.erb
<div class="col-lg-9 col-xs-12">

    <p>
    <% @banner.images.each do |image| %>
        <%= cl_image_tag(image.path, { size: '125x125', crop: :fit }) %>
    <% end %>
    </p>

    <p id="notice"><%= notice %></p>

    <div class="row">
      <div class="col-lg-4">
        <p>
          <strong>Banner 1:</strong><br>
          <%= image_tag(@banner.banner1) %>
        </p>

        <p>
          <strong>Banner 2:</strong><br>
          <%= image_tag@banner.banner2 %>
        </p>
        <p>
          <strong>Banner 3:</strong><br>
          <%= image_tag@banner.banner3 %>
        </p>
      </div>

      <div class="col-lg-4">
        <p>
          <strong>Banner 4:</strong><br>
          <%= image_tag@banner.banner4 %>
        </p>
        <p>
          <strong>Banner 5:</strong><br>
          <%= image_tag@banner.banner5 %>
        </p>
        <p>
          <strong>Banner 6:</strong><br>
          <%= image_tag@banner.banner6 %>
        </p>
      </div>

    </div>
    <div class="row">
      <%= link_to 'Edit', edit_banner_path(@banner) %> |
      <%= link_to 'Back', banners_path %>
    </div>

</div>

<br><br>