config/routes.rb
Rails.application.routes.draw do

  resources :cprofiles, path: 'admin/company-profiles'

  resources :contacts

  resources :banners, path: 'admin/banners'

  devise_for :users, :path => '', :path_names => {:sign_in => 'cmp-login', :sign_out => 'logout', :sign_up => 'cmp-register'}

  resources :users, path: 'admin/users'

  get 'single/index'

  get ':slug' => 'single#index'

  get 'admin/dashboard' => 'admin#index'

  resources :properties, path: 'admin/properties'

  get '/properties/name' => 'properties#name'

  get '/properties/property_name' => 'properties#property_name'
  
  get '/home' => 'home#index'

  get '/home/development' => 'home#develop'

  get '/listing' => 'home#listing'

  get 'landing/index' => 'home#landing'

  get 'cmp/documentation' => 'home#dokumentasi'

  get 'react/latihan' => 'home#lat_react'

   root 'home#landing'

   mount Attachinary::Engine => "/attachinary"
   

end

app/models/property.rb
class Property < ActiveRecord::Base

	validates		 				:name, :slug, :location, :status, :property_type, :price, :images, presence: true
	has_attachments 		:images, maximum: 1, accept: [:jpg, :png, :gif]
	# has_attachments 	:images, maximum: 5, accept: [:jpg, :png, :gif]

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  layout "admin_layout"

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @q = Property.ransack(params[:q])

    if user_signed_in?
      @properties = @q.result.order("created_at DESC").page(params[:page]).per_page(20)
    else
      @properties = @q.result.where("active = '1' ").order("created_at DESC").page(params[:page]).per_page(20)
    end


    @jumlah_prop = Property.where("active = '1'").count

    # @properties = Property.search(params[:search]).order("created_at DESC").page(params[:page]).per_page(5)
    
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end


  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name, :slug, :location, :status, :property_type, :bedroom, :bathroom, :price, :area, :luas_bangunan, :luas_tanah, :main_fasility, :main_description, :image_url, :image_url2, :image_url3, :image_url4, :image_url5, :image_url6, :image_url7, :image_url8, :image_url9, :image_url10, :image_url11, :image_url12, :image_description, :image_description2, :image_description3, :image_description4, :image_description5, :image_description6, :image_description7, :image_description8, :image_description9, :image_description10, :image_description11, :image_description12, :active, images: [])
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control"  %>
  </div>

  <div class="field">
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Cara menulis Alias</strong>: semua huruf kecil, tanpa spasi, spasi ganti dengan (-) Contoh: <b>di-jual-rumah-puriloka</b></span>.
    </div>
    <%= f.label :alias %> (Slug)<br>
    <%= f.text_field :slug, class:"form-control", :placeholder => 'CONTOH PENULISAN ALIAS: dijual-rumah-mewah-batam-center' %>
  </div>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.select(:location, options_for_select([
          ['Baloi','Baloi'],
          ['Barelang','Barelang'],
          ['Batam Center','Batam Center'],
          ['Botania','Botania'],
          ['Batam Kota','Batam Kota'],
          ['Batu Aji','Batu Aji'],
          ['Batu Ampar','Batu Ampar'],
          ['Bengkong','Bengkong'],
          ['Jodoh','Jodoh'],
          ['Muka Kuning','Muka Kuning'],
          ['Nagoya','Nagoya'],
          ['Sei Panas','Sei Panas'],
          ['Sekupang','Sekupang'],
          ['Sukajadi','Sukajadi'],
          ['Tg Piayu','Tg Piayu'],
          ['Tiban','Tiban']
        ], @property.location
      ),
         {:prompt => "Pilih.."},
         {class: "form-control"}
      ) %>
  </div>
  <div class="field">
    <%= f.label :status %><br>

    <%= f.select(:status, options_for_select([
          ['For Rent', 'For Rent'],
          ['Disewa Cepat!', 'Disewa Cepat'],
          ['For Sale', 'For Sale'],
          ['Dijual Cepat!', 'Dijual Cepat'],
          ['Sold !', 'Sold !' ],
          ['Leased !', 'Leased !']
      ]),
         {:prompt => "Pilih.."},
         {:class => "form-control"}
    ) %>
  </div>
  <div class="field">
    <%= f.label :property_type %><br>
    <%= f.select(:property_type, options_for_select([
                     ['Rumah', 'Rumah'],
                     ['Apartemen', 'Apartemen'],
                     ['Kantor', 'Kantor' ],
                     ['Ruko', 'Ruko'],
                     ['Tanah', 'Tanah'],
                     ['Gudang', 'Gudang']
                 ], @property.property_type
              ),
                 {:prompt => "Pilih.."},
                 {:class => "form-control"}
        ) %>
  </div>

  <div class="field">
    <%= f.label :bedroom %><br>
    <%= f.number_field :bedroom, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :bathroom %><br>
    <%= f.number_field :bathroom, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area, class:"form-control" %>
  </div>
    <br>
  <div class="field">
    <%= f.label :luas_bangunan %><br>
    <%= f.text_field :luas_bangunan, class:"form-control" %>
  </div>
    <br>
  <div class="field">
    <%= f.label :luas_tanah %><br>
    <%= f.text_field :luas_tanah, class:"form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :main_fasility, 'Fasilitas' %><br>
    <%= f.text_field :main_fasility, class:"form-control" %>
  </div>
    <br>
  <div class="field">
    <%= f.label :main_description, 'Keterangan Tambahan' %><br>
    <%= f.text_area :main_description, class:"form-control" %>
  </div>
    <br>
  <div class="field">
    <%= f.label :upload_image, "Upload Foto Utama" %><br>
    <%= f.attachinary_file_field :images %>
  </div>
    <br>
  <div>
    <%= f.label :active, 'List Aktif' %>
    <%= f.select(:active, options_for_select([
           ['Yes','1'],
           ['No','2']], @property.active),
           {:prompt => "Pilih.."},
           {class: "form-control"}
    ) %>
  </div>

  <br>

  <h3>Upload another Foto via <a href="http://cloudinary.com/">Cloudinary</a></h3>
  <div class="field">
    <%= f.label :image_url, "Foto 1" %><br>
    <%= f.text_field :image_url, class:"form-control" %>
  </div>
  <div>
    <%= f.label :image_description, "Description Foto 1" %><br>
    <%= f.text_field :image_description, class:"form-control" %>
  </div>
    <br>
  <div class="field">
    <%= f.label :image_url2, "Foto 2" %><br>
    <%= f.text_field :image_url2, class:"form-control" %>
  </div>
  <div>
    <%= f.label :image_description2, "Description Foto 2" %><br>
    <%= f.text_field :image_description2, class:"form-control" %>
  </div>
    <br>
  <div class="field">
    <%= f.label :image_url3, "Foto 3" %><br>
    <%= f.text_field :image_url3, class:"form-control" %>
  </div>
  <div>
    <%= f.label :image_description3, "Description Foto 3" %><br>
    <%= f.text_field :image_description3, class:"form-control" %>
  </div>
    <br>
  <div class="field">
    <%= f.label :image_url4, "Foto 4" %><br>
    <%= f.text_field :image_url4, class:"form-control" %>
  </div>
  <div>
    <%= f.label :image_description4, "Description Foto 4" %><br>
    <%= f.text_field :image_description4, class:"form-control" %>
  </div>
    <br>
  <div class="field">
    <%= f.label :image_url5, "Foto 5" %><br>
    <%= f.text_field :image_url5, class:"form-control" %>
  </div>
  <div>
    <%= f.label :image_url5, "Description Foto 5" %><br>
    <%= f.text_field :image_description5, class:"form-control" %>
  </div>
    <br>
  <div class="field">
    <%= f.label :image_url6, "Foto 6" %><br>
    <%= f.text_field :image_url6, class:"form-control" %>
  </div>
  <div>
    <%= f.label :image_description6, "Description Foto 6" %><br>
    <%= f.text_field :image_description6, class:"form-control" %>
  </div>
  <br>

  <!--Foto Tambahan-->

  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    <span class="glyphicon glyphicon-plus"></span>Tambah Foto?
  </button>
  <div class="collapse" id="collapseExample">
    <div class="well">

      <div class="field">
        <%= f.label :image_url7, "Foto 1" %><br>
        <%= f.text_field :image_url7, class:"form-control" %>
      </div>
      <div>
        <%= f.label :image_description7, "Description Foto 1" %><br>
        <%= f.text_field :image_description7, class:"form-control" %>
      </div>
      <br>
      <div class="field">
        <%= f.label :image_url8, "Foto 2" %><br>
        <%= f.text_field :image_url8, class:"form-control" %>
      </div>
      <div>
        <%= f.label :image_description8, "Description Foto 2" %><br>
        <%= f.text_field :image_description8, class:"form-control" %>
      </div>
      <br>
      <div class="field">
        <%= f.label :image_url9, "Foto 3" %><br>
        <%= f.text_field :image_url9, class:"form-control" %>
      </div>
      <div>
        <%= f.label :image_description9, "Description Foto 3" %><br>
        <%= f.text_field :image_description9, class:"form-control" %>
      </div>
      <br>
      <div class="field">
        <%= f.label :image_url10, "Foto 4" %><br>
        <%= f.text_field :image_url10, class:"form-control" %>
      </div>
      <div>
        <%= f.label :image_description10, "Description Foto 4" %><br>
        <%= f.text_field :image_description10, class:"form-control" %>
      </div>
      <br>
      <div class="field">
        <%= f.label :image_url11, "Foto 5" %><br>
        <%= f.text_field :image_url11, class:"form-control" %>
      </div>
      <div>
        <%= f.label :image_url11, "Description Foto 5" %><br>
        <%= f.text_field :image_description11, class:"form-control" %>
      </div>
      <br>
      <div class="field">
        <%= f.label :image_url12, "Foto 6" %><br>
        <%= f.text_field :image_url12, class:"form-control" %>
      </div>
      <div>
        <%= f.label :image_description12, "Description Foto 6" %><br>
        <%= f.text_field :image_description12, class:"form-control" %>
      </div>

    </div>
  </div>

  <br/><br/><br/>

  <div class="actions">
    <%= f.submit class:"btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/properties/edit.html.erb
	<div class="col-md-8 col-sm-9">	
		<h1>Editing Property</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @property %> |
		<%= link_to 'Back', properties_path %>

    <br><br><br><br>
  </div>

app/views/properties/index.html.erb
<div class="col-md-8 col-sm-9">  
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-md-8">
      <h1>Listing Properties</h1>
    </div>
  </div>
  
  <br>
  <% if user_signed_in? %>
    <h3><i class="fa fa-plus-square-o fa-lg"></i>&nbsp;<%= link_to 'Add Property', new_property_path %>
      | Total Active: <%= @jumlah_prop %>
    </h3>
  <% end %>
  <br>
  <table class="table">
    <thead>
      <tr>
        <!-- <th>Image</th> -->
        <!-- <th>Name</th> -->
        <!-- <th>Location</th>
        <th>Status</th>
        <th>Property type</th> -->
        <!-- <th>Bedroom</th>
        <th>Bathroom</th>
        <th>Price</th>
        <th>Area</th> -->
        <!-- <th colspan="3">Actions</th> -->
      </tr>
    </thead>

    <tbody>

      <% @properties.each do |property| %>
        <tr>
          <td>
            <% property.images.each do |image| %>
              <%= cl_image_tag(image.path, { size: '325x325', crop: :fit }) %>
            <% end %>
          </td>

          <td>
            <dl>
              <dt><h3><%= property.name %> <br>
                <% if property.active == '1' %>
                  <small><span class="label label-success">Active</span></small>
                <% else %>
                  <small><span class="label label-danger">Not Active</span></small>
                <% end %>
                </h3>
              </dt>
              <p>Alias:<%= property.slug %></p>
              <dd><i class="fa fa-calendar"></i>&nbsp;<span class='label label-primary'>Tanggal: <%= property.created_at.strftime(" %d %B %Y, %H:%M ") %></span></dd>
              <dd><i class="fa fa-check"></i>&nbsp;Lokasi: <%= property.location %></dd>
              <dd><i class="fa fa-check"></i>&nbsp;Satus: <%= property.status %></dd>
              <dd><i class="fa fa-check"></i>&nbsp;Type:  <%= property.property_type %></dd>
              <dd><i class="fa fa-check"></i>&nbsp;Bedroom: <%= property.bedroom %></dd>
              <dd><i class="fa fa-check"></i>&nbsp;Bathroom: <%= property.bathroom %></dd>
              <dd><i class="fa fa-check"></i>&nbsp;Luas area: <%= property.area %></dd>
              <!-- <dd><i class="fa fa-check"></i>&nbsp;Harga Rp.: <h4><%= property.price %></h4></dd> -->
              <dd><i class="fa fa-check"></i>&nbsp;Harga Rp.: <h4><%= number_to_currency(property.price, precision: 0, unit: "Rp.", separator: "", delimiter: ".") %></h4></dd>
            </dl>
          </td>

          <td><i class="fa fa-eye"></i>&nbsp;<%= link_to 'Show', property %></td>
          <% if user_signed_in? %>
            <td><i class="fa fa-pencil-square-o"></i><%= link_to 'Edit', edit_property_path(property) %></td>
            <td><i class="fa fa-trash"></i>&nbsp;<%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  
  <%= will_paginate @posts, :style => 'color:blue' %>

  <br><br><br><br>
</div>

app/views/properties/new.html.erb
	
	<div class="col-md-8 col-sm-9">	
		<h1>New Property</h1>

		<%= render 'form' %>

		<%= link_to 'Back', properties_path %>
	</div>

		<br><br>

app/views/properties/property_name.html.erb
<% @datas.each do |d| %>
	<div>
		<a href="#"><%= d.name %></a>
	</div>
<% end %>

app/views/properties/show.html.erb
<style>
    p {
    /*background-color: #f4f4f4;*/
  }
    .spasi {
    margin-bottom: 20px;
  }
    .box {
      border: 1px #fff solid;
      padding: 10px 10px;
      background-color: #f1f1f1;
    }
    .teks {
      font-size: 28px;
    }
</style>

<div class="container">  
  <div class="col-md-8 col-sm-9">  
    <p id="notice"><%= notice %></p>

    <p>
      <% @property.images.each do |image| %>
        <%= cl_image_tag(image.path, { size: '', crop: :fit }) %>
      <% end %>  
    </p>

    <div class="box">
        <h2><%= @property.name %></h2>
      <p>
        <strong>Alias:</strong>
        <%= @property.slug %>
      </p>
    </div>

    <div class="box">
      <strong>Location:</strong>
      <h4><%= @property.location %></h4>
    </div>

    <div class="box">
      <strong>Status:</strong>
      <h4><%= @property.status %></h4>
    </div>

    <div class="box">
      <strong>Property type:</strong>
      <h4><%= @property.property_type %></h4>
    </div>

    <div class="box">
      <strong>Bedroom:</strong>
      <h4><%= @property.bedroom %></h4>
    </div>

    <div class="box">
      <strong>Bathroom:</strong>
      <h4><%= @property.bathroom %></h4>
    </div>

    <div class="box">
      <strong>Price:</strong>
      <h4><%= number_to_currency(@property.price, precision: 0, unit: "Rp.", separator: "", delimiter: ".") %></h4>
    </div>

    <div class="box">
      <strong>Area:</strong>
      <h4><%= @property.area %></h4>
    </div>

    <div class="box">
      <strong>Luas Bangunan:</strong>
      <h4><%= @property.luas_bangunan %></h4>
    </div>

    <div class="box">
      <strong>Luas Tanah:</strong>
      <h4><%= @property.luas_tanah %></h4>
    </div>

    <div class="box">
      <strong>Fasilitas:</strong>
      <h4><%= @property.main_fasility %></h4>
    </div>

    <div class="box">
      <strong>Keterangan:</strong>
      <h4><%= @property.main_description %></h4>
    </div>

    <h3>Foto Tambahan </h3>

    <div class="row spasi">
      <div class="col-lg-6">
        <%= image_tag(@property.image_url, width: "400")  %>
        <div><i class="fa fa-sticky-note-o"></i>&nbsp;<%= @property.image_description %></div>
      </div>
      <div class="col-lg-6">
        <%= image_tag(@property.image_url2, width: "400")  %>
        <div><i class="fa fa-sticky-note-o"></i>&nbsp;<%= @property.image_description2 %></div>
      </div>
    </div>
    <div class="row spasi">
      <div class="col-lg-6">
        <%= image_tag(@property.image_url3, width: "400")  %>
        <div><i class="fa fa-sticky-note-o"></i>&nbsp;<%= @property.image_description3 %></div>
      </div>
      <div class="col-lg-6">
        <%= image_tag(@property.image_url4, width: "400")  %>
        <div><i class="fa fa-sticky-note-o"></i>&nbsp;<%= @property.image_description4 %></div>
      </div>
    </div>
    <div class="row spasi">
      <div class="col-lg-6">
        <%= image_tag(@property.image_url5, width: "400")  %>
        <div><i class="fa fa-sticky-note-o"></i>&nbsp;<%= @property.image_description5 %></div>
      </div>
      <div class="col-lg-6">
        <%= image_tag(@property.image_url6, width: "400")  %>
        <div><i class="fa fa-sticky-note-o"></i>&nbsp;<%= @property.image_description6 %></div>
      </div>
    </div>

    <br>

    <% if user_signed_in? %>
      <i class="fa fa-edit"></i>&nbsp;<%= link_to 'Edit', edit_property_path(@property) %> |
    <% end %>

    <i class="fa fa-undo"></i>&nbsp;<%= link_to 'Back', properties_path %>

  </div>  
</div>

<br><br>