config/routes.rb
Rails.application.routes.draw do

  resources :cprofiles, path: 'admin/company-profiles'

  resources :contacts

  resources :banners, path: 'admin/banners'

  devise_for :users, :path => '', :path_names => {:sign_in => 'cmp-login', :sign_out => 'logout', :sign_up => 'cmp-register'}

  resources :users, path: 'admin/users'

  get 'single/index'

  get ':slug' => 'single#index'

  get 'admin/dashboard' => 'admin#index'

  resources :properties, path: 'admin/properties'

  get '/properties/name' => 'properties#name'

  get '/properties/property_name' => 'properties#property_name'
  
  get '/home' => 'home#index'

  get '/home/development' => 'home#develop'

  get '/listing' => 'home#listing'

  get 'landing/index' => 'home#landing'

  get 'cmp/documentation' => 'home#dokumentasi'

  get 'react/latihan' => 'home#lat_react'

   root 'home#landing'

   mount Attachinary::Engine => "/attachinary"
   

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :name, :email, :nohp, :comment
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :nohp, numericality: { only_integer: true }


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  layout 'admin_layout'

  before_action :authenticate_user!, except: [:show, :create]
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice:
            'Pesan anda telah terkirim, Kami akan menghubungi anda segera!'
        }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :nohp, :comment)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :nohp, "Nomor Handphone" %><br>
    <%= f.text_field :nohp, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class:"form-control", rows:"10" %>
  </div>
  <div class="actions">
    <%= f.submit 'Send', class:"btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="container">


    <h1>Editing Contact</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @contact %> |
    <%= link_to 'Back', contacts_path %>


</div>

app/views/contacts/index.html.erb
<div class="col-lg-8">

    <h1>List Inbox Masuk</h1>

    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Nohp</th>
          <th>Comment</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @contacts.each do |contact| %>
          <tr>
            <td><%= contact.name %></td>
            <td><%= contact.email %></td>
            <td><%= contact.nohp %></td>
            <td><%= contact.comment %></td>
            <td><%= link_to 'Show', contact %></td>
            <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
            <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <% link_to 'New Contact', new_contact_path %>

</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="col-lg-6 col-lg-offset-3">

    <h1>Contact Us</h1>

    <%= render 'form' %>

    <%= link_to 'Back', contacts_path %>

  </div>
</div>

<br><br>

app/views/contacts/show.html.erb
<div class="col-lg-8" style="margin-top: 10px">

  <% if flash[:notice] %>
    <p id="notice" class="alert alert-info" role="alert"><%= notice %></p>
  <% end %>

  <div class="row text-center">
    <h3>Ini adalah Pesan anda</h3>
  </div>

  <div class="row">
    <div class="col-lg-8 col-lg-offset-2" style="border: 1px solid #f0f0f0; margin-top: 20px; padding: 10px 20px 20px 20px">
      <p>
        <strong>Name:</strong>
        <%= @contact.name %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @contact.email %>
      </p>

      <p>
        <strong>Nohp:</strong>
        <%= @contact.nohp %>
      </p>

      <p>
        <strong>Comment:</strong>
        <%= @contact.comment %>
      </p>

    </div>
  </div>
  <br>
  <div class="row">
    <% if user_signed_in? %>
        <% link_to 'Edit', edit_contact_path(@contact) %>
        <%= link_to 'Back', contacts_path %> <br>
    <% end %>
  </div>
  <br>
  <div class="row text-center">
    <% if user_signed_in? %>
        <p></p>
    <% else %>
        <p>Kembali ke halaman semula <i><u><%= link_to 'Home', root_path %></u></i></p>
    <% end %>
  </div>

</div>