config/routes.rb
Rails.application.routes.draw do

  resources :cprofiles, path: 'admin/company-profiles'

  resources :contacts

  resources :banners, path: 'admin/banners'

  devise_for :users, :path => '', :path_names => {:sign_in => 'cmp-login', :sign_out => 'logout', :sign_up => 'cmp-register'}

  resources :users, path: 'admin/users'

  get 'single/index'

  get ':slug' => 'single#index'

  get 'admin/dashboard' => 'admin#index'

  resources :properties, path: 'admin/properties'

  get '/properties/name' => 'properties#name'

  get '/properties/property_name' => 'properties#property_name'
  
  get '/home' => 'home#index'

  get '/home/development' => 'home#develop'

  get '/listing' => 'home#listing'

  get 'landing/index' => 'home#landing'

  get 'cmp/documentation' => 'home#dokumentasi'

  get 'react/latihan' => 'home#lat_react'

   root 'home#landing'

   mount Attachinary::Engine => "/attachinary"
   

end

app/models/cprofile.rb
class Cprofile < ActiveRecord::Base
end

app/controllers/cprofiles_controller.rb
class CprofilesController < ApplicationController
  before_action :set_cprofile, only: [:show, :edit, :update, :destroy]

  # GET /cprofiles
  # GET /cprofiles.json
  def index
    @cprofiles = Cprofile.all
  end

  # GET /cprofiles/1
  # GET /cprofiles/1.json
  def show
  end

  # GET /cprofiles/new
  def new
    @cprofile = Cprofile.new
  end

  # GET /cprofiles/1/edit
  def edit
  end

  # POST /cprofiles
  # POST /cprofiles.json
  def create
    @cprofile = Cprofile.new(cprofile_params)

    respond_to do |format|
      if @cprofile.save
        format.html { redirect_to @cprofile, notice: 'Cprofile was successfully created.' }
        format.json { render :show, status: :created, location: @cprofile }
      else
        format.html { render :new }
        format.json { render json: @cprofile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cprofiles/1
  # PATCH/PUT /cprofiles/1.json
  def update
    respond_to do |format|
      if @cprofile.update(cprofile_params)
        format.html { redirect_to @cprofile, notice: 'Cprofile was successfully updated.' }
        format.json { render :show, status: :ok, location: @cprofile }
      else
        format.html { render :edit }
        format.json { render json: @cprofile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cprofiles/1
  # DELETE /cprofiles/1.json
  def destroy
    @cprofile.destroy
    respond_to do |format|
      format.html { redirect_to cprofiles_url, notice: 'Cprofile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cprofile
      @cprofile = Cprofile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cprofile_params
      params.require(:cprofile).permit(:company_name, :company_phone, :company_mail, :company_address, :company_owner, :company_web, :company_description, :company_logo)
    end
end

app/helpers/cprofiles_helper.rb
module CprofilesHelper
end

app/views/cprofiles/_form.html.erb
<%= form_for(@cprofile) do |f| %>
  <% if @cprofile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cprofile.errors.count, "error") %> prohibited this cprofile from being saved:</h2>

      <ul>
      <% @cprofile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :company_phone %><br>
    <%= f.text_field :company_phone %>
  </div>
  <div class="field">
    <%= f.label :company_mail %><br>
    <%= f.text_field :company_mail %>
  </div>
  <div class="field">
    <%= f.label :company_address %><br>
    <%= f.text_area :company_address %>
  </div>
  <div class="field">
    <%= f.label :company_owner %><br>
    <%= f.text_field :company_owner %>
  </div>
  <div class="field">
    <%= f.label :company_web %><br>
    <%= f.text_field :company_web %>
  </div>
  <div class="field">
    <%= f.label :company_description %><br>
    <%= f.text_area :company_description %>
  </div>
  <div class="field">
    <%= f.label :company_logo %><br>
    <%= f.text_field :company_logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cprofiles/edit.html.erb
<h1>Editing Cprofile</h1>

<%= render 'form' %>

<%= link_to 'Show', @cprofile %> |
<%= link_to 'Back', cprofiles_path %>

app/views/cprofiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Company Profiles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Company name</th>
      <th>Company phone</th>
      <th>Company mail</th>
      <!--<th>Company address</th>-->
      <th>Company owner</th>
      <th>Company web</th>
      <!--<th>Company description</th>-->
      <!--<th>Company logo</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cprofiles.each do |cprofile| %>
      <tr>
        <td><%= cprofile.company_name %></td>
        <td><%= cprofile.company_phone %></td>
        <td><%= cprofile.company_mail %></td>
        <!--<td><%= cprofile.company_address %></td>-->
        <td><%= cprofile.company_owner %></td>
        <td><%= cprofile.company_web %></td>
        <!--<td><%= cprofile.company_description %></td>-->
        <!--<td><%= cprofile.company_logo %></td>-->
        <td><%= link_to 'Show', cprofile %></td>
        <td><%= link_to 'Edit', edit_cprofile_path(cprofile) %></td>
        <td><%= link_to 'Destroy', cprofile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cprofile', new_cprofile_path %>

app/views/cprofiles/new.html.erb
<h1>New Cprofile</h1>

<%= render 'form' %>

<%= link_to 'Back', cprofiles_path %>

app/views/cprofiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @cprofile.company_name %>
</p>

<p>
  <strong>Company phone:</strong>
  <%= @cprofile.company_phone %>
</p>

<p>
  <strong>Company mail:</strong>
  <%= @cprofile.company_mail %>
</p>

<p>
  <strong>Company address:</strong>
  <%= @cprofile.company_address %>
</p>

<p>
  <strong>Company owner:</strong>
  <%= @cprofile.company_owner %>
</p>

<p>
  <strong>Company web:</strong>
  <%= @cprofile.company_web %>
</p>

<p>
  <strong>Company description:</strong>
  <%= @cprofile.company_description %>
</p>

<p>
  <strong>Company logo:</strong>
  <%= @cprofile.company_logo %>
</p>

<%= link_to 'Edit', edit_cprofile_path(@cprofile) %> |
<%= link_to 'Back', cprofiles_path %>